[package]
name = "cedar-dotnet-ffi"
version = "0.1.0"
edition = "2024"

[lib]
crate-type=["cdylib"]

[dependencies]
serde_json = "1.0.141"

[dependencies.cedar-policy]
version = "4.7.0"
git = "https://github.com/cedar-policy/cedar"
branch = "main"
features = ["partial-eval"]
